"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let toPerson = "sAMRINA";
let person = toPerson.toUpperCase();
let person2 = toPerson.toLowerCase();
let person3 = (toPerson.charAt(0).toUpperCase() + toPerson.slice(1).toLowerCase());
;
;
console.log(person);
console.log(person2);
console.log(person3);
