"use strict";
// True
Object.defineProperty(exports, "__esModule", { value: true });
console.log('\n');
/*1.*/ let largestCountry = "Russia";
console.log("Is largestCountry == 'Russia? I predict True.");
console.log(largestCountry == "Russia");
console.log('\n');
/*2.*/ let largestMountain = "MountEverest";
console.log("Is largestMountain == 'MountEverest'? I predict True.");
console.log(largestMountain == "MountEverest");
console.log('\n');
/*3.*/ let kingOfFruit = "Mango";
console.log("Is kingOfFruit == 'Mango'? I predict True.");
console.log(kingOfFruit == "Mango");
console.log('\n');
/*4.*/ let smallestBeing = "Microbe";
console.log("Is SmallestBeing == 'Microbe'? I predict True.");
console.log(smallestBeing == "Microbe");
console.log('\n');
/*5.*/ let largestForest = "AmazonRainForest";
console.log("Is largestForest == 'AmazonRainForest'? I predict True.");
console.log(largestForest == "AmazonRainForest");
// False
console.log('\n');
/*6.*/ let handFingers = 8;
console.log("Is handFingers == '10'? I predict True.");
console.log(handFingers == 10);
console.log('\n');
/*7.*/ let appleColor = "green";
console.log("Is appleColor == 'yellow'? I predict True.");
console.log(appleColor == "yellow");
console.log('\n');
/*8.*/ let alphabets = 26;
console.log("Is alphabets == '16'? I predict True.");
console.log(alphabets == 16);
console.log('\n');
/*9.*/ let ramdanDays = 30 || 29;
console.log("Is ramdanDays == '32 || 33'? I predict True.");
console.log(ramdanDays == 32 || 33);
console.log('\n');
/*10.*/ let favoriteGame = "Yandere Simulator";
console.log("Is a == 'afk journey'? I predict True.");
console.log(favoriteGame == "afk journey");
